deltree /Y \pt
xcopy *.* \pt\ /s
del c:\pt\*.pas
del c:\pt\*.tpu
del c:\pt\*.asm
del c:\pt\*.obj
del c:\pt\*.bat
del c:\pt\font.exe
del c:\pt\route*.exe
del c:\pt\tileconv.exe
del c:\pt\manconv.exe
del c:\pt\itemconv.exe
del c:\pt\depconv.exe
del c:\pt\chop.exe
del c:\pt\intropt.exe
del c:\pt\pcxconv.exe
del c:\pt\data\groups.da0
del c:\pt\register.txt
del c:\pt\install.exe
del c:\pt\payback.cfg
del c:\pt\unmain.pic
del c:\pt\regmain.pic
del c:\pt\maps\*.map
del c:\pt\gamedata\game3.dat
del c:\pt\gamedata\game4.dat
del c:\pt\gamedata\game5.dat
del c:\pt\gamedata\game6.dat
del c:\pt\regist.lst
del c:\pt\revision.txt
cd\pt21
