tpc sbunit.pas -$e+ -$g+ -$n+ -$a+ -$l- -$s- -$i-
tpc varunit.pas -$e+ -$g+ -$n+ -$a+ -$l- -$s- -$i-
tpc extunit.pas -$e+ -$g+ -$n+ -$a+ -$l- -$s- -$i-
tpc pbtunit.pas -$e+ -$g+ -$n+ -$a+ -$l- -$s- -$i-
tpc 3dgame.pas -$e+ -$g+ -$n+ -$a+ -$l- -$s- -$i-
tpc payback.pas -$e+ -$g+ -$n+ -$a+ -$l- -$s- -$i-
copy 3dgame.exe game1.dat
copy grouped.exe game2.dat
copy weaponed.exe game3.dat
copy itemed.exe game4.dat
copy mapedit.exe game5.dat
copy viewfile.exe game6.dat
grpload.bat